version: "3.8"
services:
 app:
  image: eva:0.0.9
  build: .
  depends_on:
   - db
  ports:
   - ${PORT}:3000
  env_file: .env
  volumes:
   - .:/usr/src
  command: npx nodemon ./src/index.js

 db:
  image: postgres:14.4
  restart: unless-stopped
  environment: 
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_DB: ${POSTGRES_DB}
  ports:
   - ${POSTGRES_PORT}:5432
  volumes:
   - psql_volume:/var/lib/postgresql/data

volumes:
 psql_volume: