version: "3.8"
services:
 app:
  image: eva:0.9.0
  build: .
  depends_on:
   - db
  ports:
   - ${PORT_DEV}:3000
  environment:
   - NODE_ENV=dev
  env_file: .env
  volumes:
   - .:/usr/src
  command: npx nodemon ./src/index.js

 db:
  image: postgres:14.4
  restart: unless-stopped
  environment: 
   POSTGRES_USER: ${PG_USER_DEV}
   POSTGRES_PASSWORD: ${PG_PASS_DEV}
   POSTGRES_DB: ${PG_DB_DEV}
  ports:
   - ${PG_PORT_DEV}:5432
  volumes:
   - psql_volume:/var/lib/postgresql/data

volumes:
 psql_volume: